name: Deploy to Google Cloud Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy generate-meet-link \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source . \
          --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=service-account-key.json